"""Step 3 M2.e: DROP the legacy conversations + 6 FTS shadow tables.

Preconditions (run step3_verify_drop_safety.py first, exit code must
be 0 → Z=0). A separate pre-Step-3 backup exists under
``~/lapwing-backups/pre_step3_*/``; see docs/refactor_v2/backup_conventions.md.

Tables dropped (7 total):

    conversations
    conversations_fts
    conversations_fts_config
    conversations_fts_content
    conversations_fts_data
    conversations_fts_docsize
    conversations_fts_idx

``conversations_fts`` is an FTS5 virtual table; its 5 ``_config /
_content / _data / _docsize / _idx`` shadow tables are autogenerated
and must be dropped explicitly because ``DROP TABLE
conversations_fts`` alone does not remove every shadow on every SQLite
version (SQLite 3.50+ handles it, earlier versions require manual).

Modes:
    --dry-run : list the tables + current row counts; no writes.
    --execute : DROP them. Post-execute, SELECT from sqlite_master
                verifies each name is absent and exits non-zero if any
                remain.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

_TABLES_TO_DROP: tuple[str, ...] = (
    "conversations",
    "conversations_fts",
    "conversations_fts_config",
    "conversations_fts_content",
    "conversations_fts_data",
    "conversations_fts_docsize",
    "conversations_fts_idx",
)


def _existing(db: sqlite3.Connection, name: str) -> bool:
    cur = db.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name = ?",
        (name,),
    )
    return cur.fetchone() is not None


def _row_count(db: sqlite3.Connection, name: str) -> int | None:
    try:
        cur = db.execute(f"SELECT COUNT(*) FROM {name}")
        return cur.fetchone()[0]
    except sqlite3.OperationalError:
        return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", default="data/lapwing.db")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--execute", action="store_true")
    args = parser.parse_args()

    if args.dry_run == args.execute:
        print("error: pass exactly one of --dry-run / --execute", file=sys.stderr)
        return 2

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"error: {db_path} does not exist", file=sys.stderr)
        return 2

    db = sqlite3.connect(db_path)
    try:
        print(f"target: {db_path.resolve()}")
        print("tables to drop (7):")
        for name in _TABLES_TO_DROP:
            rows = _row_count(db, name)
            exists = _existing(db, name)
            if not exists:
                note = "MISSING"
            elif rows is None:
                note = "untouchable"
            else:
                note = f"{rows} rows"
            print(f"  - {name:<30} [{note}]")

        if args.dry_run:
            print("\ndry-run complete, nothing written")
            return 0

        # --execute path. FTS5 virtual-table DROP first (one statement
        # can cascade on newer SQLite), then explicit shadow-table
        # DROPs as a belt + braces. ``IF EXISTS`` for idempotency.
        for name in _TABLES_TO_DROP:
            db.execute(f"DROP TABLE IF EXISTS {name}")
        db.commit()
        print("\nDROP TABLE IF EXISTS executed for all 7 names")

        # Verify via sqlite_master — zero of these names should remain.
        survived: list[str] = []
        for name in _TABLES_TO_DROP:
            if _existing(db, name):
                survived.append(name)

        if survived:
            print("post-drop survivors (FAIL):")
            for name in survived:
                print(f"  - {name}")
            return 1

        print("verification: every target name is absent from sqlite_master")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    sys.exit(main())
