"""Sandbox skill execution wrapper. Generated by SkillExecutor at runtime."""
import json
import sys
import importlib.util


def main():
    args = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {}
    spec = importlib.util.spec_from_file_location("skill", "/workspace/skill.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    result = mod.run(**args)
    print(json.dumps(result, ensure_ascii=False, default=str))


if __name__ == "__main__":
    main()
