"""MemoryCandidate / CompiledMemoryPatch model tests (Phase 2)."""

from __future__ import annotations

import pytest

from src.memory.candidate import (
    CompiledMemoryPatch,
    MemoryCandidate,
    Relation,
)


def _candidate(**overrides) -> MemoryCandidate:
    base = dict(
        source_ids=["traj:1"],
        subject="entity.kevin",
        predicate="prefers",
        object="blueprint-first工作方式",
        type="preference",
        salience=0.85,
        confidence=0.9,
        stability="long_lived",
        privacy_level="personal",
    )
    base.update(overrides)
    return MemoryCandidate(**base)


def test_candidate_id_autogenerated():
    c = _candidate()
    assert c.id.startswith("candidate:")


def test_candidate_id_can_be_overridden():
    c = _candidate(id="candidate:abc123")
    assert c.id == "candidate:abc123"


def test_salience_must_be_in_range():
    with pytest.raises(Exception):
        _candidate(salience=1.5)
    with pytest.raises(Exception):
        _candidate(salience=-0.1)


def test_confidence_must_be_in_range():
    with pytest.raises(Exception):
        _candidate(confidence=2.0)


def test_stability_must_be_valid_enum():
    with pytest.raises(Exception):
        _candidate(stability="forever")


def test_privacy_must_be_valid_enum():
    with pytest.raises(Exception):
        _candidate(privacy_level="public2")


def test_relations_serialize_round_trip():
    c = _candidate(relations=[Relation(type="creator_of", target="entity.lapwing")])
    payload = c.model_dump_json()
    restored = MemoryCandidate.model_validate_json(payload)
    assert restored.relations[0].type == "creator_of"
    assert restored.relations[0].target == "entity.lapwing"


def test_candidate_full_round_trip():
    c = _candidate(
        evidence_quote="Kevin: 我喜欢 blueprint 先行",
        contradiction_risk=0.1,
        relations=[Relation(type="related_to", target="entity.lapwing")],
    )
    payload = c.model_dump_json()
    restored = MemoryCandidate.model_validate_json(payload)
    assert restored.evidence_quote == c.evidence_quote
    assert restored.contradiction_risk == c.contradiction_risk
    assert restored.subject == c.subject


def test_compiled_patch_round_trip():
    p = CompiledMemoryPatch(
        target_page_id="entity.kevin",
        target_path="data/memory/wiki/entities/kevin.md",
        operation="add_fact",
        section="Stable facts",
        content="- prefers blueprint-first",
        reason="distilled from candidate",
        source_ids=["traj:1"],
        before_hash="abc",
        candidate_id="candidate:00000001",
    )
    restored = CompiledMemoryPatch.model_validate_json(p.model_dump_json())
    assert restored.operation == "add_fact"
    assert restored.before_hash == "abc"
    assert restored.risk == "low"


def test_compiled_patch_default_risk_is_low():
    p = CompiledMemoryPatch(
        target_page_id="entity.kevin",
        target_path="x.md",
        operation="create",
        content="...",
        reason="r",
        source_ids=[],
        candidate_id="c1",
    )
    assert p.risk == "low"
